import {
  CUSTOM_EXAMPLE_PATH,
  GAP_DEPENDENT,
  SHRINK_DEPENDENT,
  TRAITS,
  localized,
  type ExampleGuideSource,
} from "./guideShared";

export const EXAMPLE_GUIDES: Record<string, ExampleGuideSource> = {
  [CUSTOM_EXAMPLE_PATH]: {
    title: localized(
      "自分のソート",
      "Your Sort",
      "自定义排序",
      "Tu ordenamiento",
      "Sua ordenação",
      "나만의 정렬",
      "Votre tri",
      "Eigener Sortieralgorithmus",
    ),
    summary: localized(
      "最小限の関数から始めて、配列を昇順に並べる方法を自由に実装できます。",
      "Start with a minimal function and sort the array in ascending order any way you choose.",
      "从最小函数开始，用你选择的方法把数组按升序排列。",
      "Empieza con una función mínima y ordena el arreglo de forma ascendente como prefieras.",
      "Comece com uma função mínima e ordene o array em ordem crescente como preferir.",
      "최소한의 함수에서 시작해 원하는 방법으로 배열을 오름차순 정렬할 수 있습니다.",
      "Partez d’une fonction minimale et triez le tableau par ordre croissant comme vous le souhaitez.",
      "Beginne mit einer minimalen Funktion und sortiere das Array auf deine eigene Weise aufsteigend.",
    ),
    focus: localized(
      "比較・交換・代入を通常のPythonで書くだけで、配列の動きが自動的に可視化されます。",
      "Write ordinary Python comparisons, swaps, and assignments; every array change is visualized automatically.",
      "只需使用普通的 Python 编写比较、交换和赋值，数组的每个变化都会自动可视化。",
      "Escribe comparaciones, intercambios y asignaciones en Python normal; cada cambio del arreglo se visualiza automáticamente.",
      "Escreva comparações, trocas e atribuições em Python comum; cada mudança no array é visualizada automaticamente.",
      "일반 Python으로 비교, 교환, 대입을 작성하면 배열의 모든 변화가 자동으로 시각화됩니다.",
      "Écrivez des comparaisons, échanges et affectations en Python ordinaire : chaque modification du tableau est visualisée automatiquement.",
      "Schreibe Vergleiche, Tauschvorgänge und Zuweisungen in normalem Python; jede Änderung am Array wird automatisch visualisiert.",
    ),
    best: "—",
    average: "—",
    worst: "—",
    trait: localized(
      "実装次第",
      "Up to your implementation",
      "取决于你的实现",
      "Depende de tu implementación",
      "Depende da sua implementação",
      "구현에 따라 다름",
      "Selon votre implémentation",
      "Abhängig von deiner Implementierung",
    ),
  },
  "sort_examples/insertion_sort.py": {
    title: "Insertion Sort",
    summary: localized(
      "左側の整列済み部分へ、次の値を正しい位置まで差し込みます。",
      "Inserts each next value into its correct position in the sorted left side.",
      "将下一个值插入左侧已排序部分的正确位置。",
      "Inserta cada valor siguiente en su posición correcta dentro de la parte izquierda ordenada.",
      "Insere cada próximo valor na posição correta da parte esquerda já ordenada.",
      "다음 값을 왼쪽의 정렬된 구간에서 올바른 위치에 삽입합니다.",
      "Insère chaque nouvelle valeur à sa place dans la partie gauche déjà triée.",
      "Fügt jeden nächsten Wert an der richtigen Stelle in den bereits sortierten linken Bereich ein.",
    ),
    focus: localized(
      "「ほぼ整列済み」に変えると、値をずらす回数が少なくなることに注目しましょう。",
      "Try “Nearly sorted” and notice how few values need to move.",
      "选择“接近有序”，观察需要移动的值会变少。",
      "Prueba «Casi ordenado» y observa cuántos pocos valores deben moverse.",
      "Experimente “Quase ordenado” e observe como poucos valores precisam se mover.",
      "‘거의 정렬됨’을 선택하고 이동해야 하는 값이 얼마나 적은지 살펴보세요.",
      "Essayez « Presque trié » et observez le faible nombre de valeurs à déplacer.",
      "Probiere „Fast sortiert“ und beobachte, wie wenige Werte verschoben werden müssen.",
    ),
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    trait: TRAITS.stableInPlace,
  },
  "sort_examples/bubble_sort.py": {
    title: "Bubble Sort",
    summary: localized(
      "隣り合う値を比べ、大きい値を右端へ少しずつ運びます。",
      "Compares neighbors and gradually carries larger values to the right.",
      "比较相邻值，并逐步把较大的值移到右侧。",
      "Compara valores vecinos y lleva gradualmente los mayores hacia la derecha.",
      "Compara valores vizinhos e leva gradualmente os maiores para a direita.",
      "이웃한 값을 비교해 큰 값을 조금씩 오른쪽으로 보냅니다.",
      "Compare les valeurs voisines et déplace progressivement les plus grandes vers la droite.",
      "Vergleicht benachbarte Werte und bewegt größere Werte schrittweise nach rechts.",
    ),
    focus: localized(
      "一周するたび右端が確定色に変わります。「逆順」で交換の多さを比べてみましょう。",
      "The right edge settles after each pass. Try “Reversed” to see the swaps multiply.",
      "每轮结束后右端会确定下来。选择“逆序”，观察交换次数如何增加。",
      "El extremo derecho queda fijado tras cada pasada. Prueba «Invertido» para ver cómo aumentan los intercambios.",
      "A extremidade direita é definida a cada passagem. Use “Invertido” para ver as trocas aumentarem.",
      "한 번 훑을 때마다 오른쪽 끝이 확정됩니다. ‘역순’에서 교환이 늘어나는 모습을 보세요.",
      "L’extrémité droite se fixe après chaque passage. Essayez « Inversé » pour voir les échanges se multiplier.",
      "Nach jedem Durchlauf steht der rechte Rand fest. Mit „Umgekehrt“ werden die vielen Tauschvorgänge sichtbar.",
    ),
    best: "O(n²)",
    average: "O(n²)",
    worst: "O(n²)",
    trait: TRAITS.stableInPlace,
  },
  "sort_examples/selection_sort.py": {
    title: "Selection Sort",
    summary: localized(
      "未整列部分の最小値を探し、先頭の値と入れ替えます。",
      "Finds the smallest unsorted value and swaps it into the first open position.",
      "找出未排序部分的最小值，并把它交换到最前面的空位。",
      "Busca el menor valor sin ordenar y lo intercambia con la primera posición libre.",
      "Encontra o menor valor não ordenado e o troca com a primeira posição livre.",
      "정렬되지 않은 구간의 최솟값을 찾아 맨 앞의 빈 위치와 교환합니다.",
      "Cherche la plus petite valeur non triée et l’échange avec la première position libre.",
      "Sucht den kleinsten unsortierten Wert und tauscht ihn an die erste freie Position.",
    ),
    focus: localized(
      "入力の並び方を変えても、最小値を探す比較回数がほぼ変わらない点が特徴です。",
      "Change the input pattern and notice that the number of comparisons barely changes.",
      "改变输入模式，观察寻找最小值所需的比较次数几乎不变。",
      "Cambia el patrón de entrada y observa que el número de comparaciones apenas cambia.",
      "Mude o padrão de entrada e note que o número de comparações quase não muda.",
      "입력 패턴을 바꿔도 최솟값을 찾는 비교 횟수가 거의 같다는 점을 살펴보세요.",
      "Changez le type d’entrée et constatez que le nombre de comparaisons varie à peine.",
      "Ändere das Eingabemuster und beobachte, dass sich die Zahl der Vergleiche kaum verändert.",
    ),
    best: "O(n²)",
    average: "O(n²)",
    worst: "O(n²)",
    trait: TRAITS.unstableInPlace,
  },
  "sort_examples/cocktail_sort.py": {
    title: "Cocktail Sort",
    summary: localized(
      "左右へ交互に走査し、大きい値と小さい値を両端へ運びます。",
      "Alternates directions, carrying large and small values toward both ends.",
      "交替向左右扫描，把大值和小值分别送到两端。",
      "Alterna la dirección y lleva los valores grandes y pequeños hacia ambos extremos.",
      "Alterna a direção, levando valores grandes e pequenos para as duas extremidades.",
      "방향을 번갈아 훑으며 큰 값과 작은 값을 양쪽 끝으로 보냅니다.",
      "Alterne les directions pour déplacer les grandes et petites valeurs vers les deux extrémités.",
      "Wechselt die Richtung und bewegt große sowie kleine Werte zu beiden Enden.",
    ),
    focus: localized(
      "確定色が右端と左端から交互に増える様子を、Bubble Sortと比べましょう。",
      "Compare its alternating settled edges with Bubble Sort’s one-way passes.",
      "观察两端交替确定的过程，并与 Bubble Sort 的单向扫描比较。",
      "Compara sus extremos fijados de forma alterna con las pasadas en una dirección de Bubble Sort.",
      "Compare as extremidades definidas alternadamente com as passagens em uma direção do Bubble Sort.",
      "양쪽 끝이 번갈아 확정되는 모습을 Bubble Sort의 한 방향 진행과 비교해 보세요.",
      "Comparez ses extrémités fixées en alternance aux passages à sens unique de Bubble Sort.",
      "Vergleiche die abwechselnd feststehenden Ränder mit den einseitigen Durchläufen von Bubble Sort.",
    ),
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    trait: TRAITS.stableInPlace,
  },
  "sort_examples/gnome_sort.py": {
    title: "Gnome Sort",
    summary: localized(
      "順序が正しければ前へ進み、逆なら交換して一歩戻ります。",
      "Walks forward when neighbors are ordered, or swaps and steps back when they are not.",
      "相邻值有序时前进，否则交换并后退一步。",
      "Avanza si los vecinos están ordenados; si no, los intercambia y retrocede.",
      "Avança quando os vizinhos estão ordenados; caso contrário, troca e volta um passo.",
      "이웃한 값의 순서가 맞으면 앞으로 가고, 아니면 교환한 뒤 한 칸 돌아갑니다.",
      "Avance lorsque les voisins sont ordonnés, sinon les échange et recule d’un pas.",
      "Geht vorwärts, wenn Nachbarn geordnet sind, sonst werden sie getauscht und ein Schritt zurückgegangen.",
    ),
    focus: localized(
      "値が正しい場所へ戻るまで、同じ要素が左へ歩く様子を追ってみましょう。",
      "Follow one value as it walks left until it reaches the correct position.",
      "跟随一个值向左移动，直到它到达正确位置。",
      "Sigue un valor mientras camina hacia la izquierda hasta llegar a su posición correcta.",
      "Acompanhe um valor andando para a esquerda até chegar à posição correta.",
      "하나의 값이 올바른 위치에 닿을 때까지 왼쪽으로 이동하는 과정을 따라가 보세요.",
      "Suivez une valeur pendant qu’elle se déplace vers la gauche jusqu’à sa bonne position.",
      "Verfolge einen Wert auf seinem Weg nach links bis zur richtigen Position.",
    ),
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    trait: TRAITS.stableInPlace,
  },
  "sort_examples/odd_even_sort.py": {
    title: "Odd-Even Sort",
    summary: localized(
      "奇数位置の組と偶数位置の組を交互に比べ、隣接交換を繰り返します。",
      "Alternates odd and even pairs, repeatedly swapping neighboring values.",
      "交替比较奇数位和偶数位的配对，并反复交换相邻值。",
      "Alterna pares impares y pares, intercambiando repetidamente valores vecinos.",
      "Alterna pares de posições ímpares e pares, trocando repetidamente valores vizinhos.",
      "홀수 위치 쌍과 짝수 위치 쌍을 번갈아 비교하며 이웃한 값을 계속 교환합니다.",
      "Alterne les paires impaires et paires en échangeant plusieurs fois les valeurs voisines.",
      "Wechselt zwischen ungeraden und geraden Paaren und tauscht wiederholt benachbarte Werte.",
    ),
    focus: localized(
      "同時に処理できる比較の組が、奇数側と偶数側で切り替わる点に注目しましょう。",
      "Notice how independent comparison pairs alternate between odd and even phases.",
      "观察可同时处理的独立比较对如何在奇偶阶段之间切换。",
      "Observa cómo los pares independientes cambian entre las fases impar y par.",
      "Observe como os pares independentes alternam entre as fases ímpar e par.",
      "동시에 처리할 수 있는 독립 비교 쌍이 홀수 단계와 짝수 단계에서 바뀌는 점을 보세요.",
      "Observez comment les paires indépendantes alternent entre les phases impaire et paire.",
      "Beobachte, wie unabhängige Vergleichspaare zwischen ungeraden und geraden Phasen wechseln.",
    ),
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    trait: TRAITS.stableInPlace,
  },
  "sort_examples/shell_sort.py": {
    title: "Shell Sort",
    summary: localized(
      "離れた要素を先に整え、間隔を縮めながら挿入ソートへ近づけます。",
      "Orders distant values first, then shrinks the gap toward Insertion Sort.",
      "先整理相距较远的值，再缩小间隔，逐步接近插入排序。",
      "Ordena primero valores distantes y reduce el intervalo hasta acercarse a Insertion Sort.",
      "Ordena primeiro valores distantes e reduz o intervalo até se aproximar do Insertion Sort.",
      "멀리 떨어진 값을 먼저 정리한 뒤 간격을 줄이며 Insertion Sort에 가까워집니다.",
      "Ordonne d’abord les valeurs éloignées, puis réduit l’intervalle jusqu’à rejoindre Insertion Sort.",
      "Ordnet zuerst weit entfernte Werte und verkleinert dann die Lücke bis hin zu Insertion Sort.",
    ),
    focus: localized(
      "note「gap」が小さくなるたび、比較する距離がどう変わるか見てみましょう。",
      "Follow the “gap” note and watch the comparison distance shrink.",
      "跟随“gap”提示，观察比较距离如何逐渐缩短。",
      "Sigue la nota «gap» y observa cómo se reduce la distancia de comparación.",
      "Acompanhe a nota “gap” e veja a distância de comparação diminuir.",
      "‘gap’ 메모를 따라 비교 거리가 줄어드는 모습을 살펴보세요.",
      "Suivez la note « gap » et observez la distance de comparaison diminuer.",
      "Folge dem Hinweis „gap“ und beobachte, wie der Vergleichsabstand kleiner wird.",
    ),
    best: GAP_DEPENDENT,
    average: GAP_DEPENDENT,
    worst: "O(n²)",
    trait: TRAITS.unstableInPlace,
  },
  "sort_examples/comb_sort.py": {
    title: "Comb Sort",
    summary: localized(
      "大きな間隔の比較で遠くの逆転を直し、間隔を1まで縮めます。",
      "Fixes distant inversions with a large gap, then shrinks that gap to one.",
      "用较大的间隔修正远处的逆序，再把间隔缩小到 1。",
      "Corrige inversiones lejanas con un intervalo grande y luego lo reduce hasta uno.",
      "Corrige inversões distantes com um intervalo grande e depois o reduz até um.",
      "큰 간격으로 멀리 있는 역전을 바로잡은 뒤 간격을 1까지 줄입니다.",
      "Corrige les inversions éloignées avec un grand intervalle, puis le réduit jusqu’à un.",
      "Behebt weit entfernte Fehlordnungen mit einer großen Lücke und verkleinert sie anschließend auf eins.",
    ),
    focus: localized(
      "note「gap」を追い、離れた小さい値が一度に大きく動く様子を見てみましょう。",
      "Follow the “gap” note and watch small values make large jumps.",
      "跟随“gap”提示，观察远处的小值如何一次跨越较大距离。",
      "Sigue la nota «gap» y observa cómo los valores pequeños dan saltos grandes.",
      "Acompanhe a nota “gap” e veja valores pequenos darem grandes saltos.",
      "‘gap’ 메모를 따라 작은 값이 한 번에 크게 이동하는 모습을 보세요.",
      "Suivez la note « gap » et observez les petites valeurs effectuer de grands sauts.",
      "Folge dem Hinweis „gap“ und beobachte, wie kleine Werte große Sprünge machen.",
    ),
    best: SHRINK_DEPENDENT,
    average: SHRINK_DEPENDENT,
    worst: "O(n²)",
    trait: TRAITS.unstableInPlace,
  },
  "sort_examples/merge_sort.py": {
    title: "Merge Sort",
    summary: localized(
      "配列を半分ずつに分け、整列済みの小さな列として結合します。",
      "Splits the array into halves, then merges small sorted sequences.",
      "把数组不断分成两半，再将已排序的小序列合并起来。",
      "Divide el arreglo en mitades y luego combina pequeñas secuencias ordenadas.",
      "Divide o array em metades e depois combina pequenas sequências ordenadas.",
      "배열을 절반씩 나눈 뒤 정렬된 작은 수열로 다시 합칩니다.",
      "Divise le tableau en moitiés, puis fusionne de petites séquences triées.",
      "Teilt das Array in Hälften und führt kleine sortierte Folgen wieder zusammen.",
    ),
    focus: localized(
      "書き換えが連続する区間に注目すると、左右の列を一つに戻す過程が見えてきます。",
      "Watch each continuous write region as the left and right halves merge.",
      "观察连续写入的区域，看看左右两半如何合并为一个序列。",
      "Observa cada zona de escritura continua mientras se combinan las mitades izquierda y derecha.",
      "Observe cada região de escrita contínua enquanto as metades esquerda e direita são combinadas.",
      "연속으로 값이 쓰이는 구간을 보며 왼쪽과 오른쪽 절반이 합쳐지는 과정을 살펴보세요.",
      "Observez chaque zone d’écriture continue pendant la fusion des moitiés gauche et droite.",
      "Beobachte die zusammenhängenden Schreibbereiche, während linke und rechte Hälfte verschmelzen.",
    ),
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    trait: TRAITS.stableExtraN,
  },
  "sort_examples/quick_sort.py": {
    title: "Quick Sort",
    summary: localized(
      "基準値 pivot より小さい側と大きい側に分け、同じ処理を再帰します。",
      "Partitions values around a pivot, then recursively repeats on both sides.",
      "以 pivot 为基准把值分到两侧，再递归处理两边。",
      "Divide los valores alrededor de un pivot y repite el proceso recursivamente en ambos lados.",
      "Divide os valores em torno de um pivot e repete recursivamente nos dois lados.",
      "pivot을 기준으로 값을 양쪽에 나눈 뒤 두 구간에서 같은 작업을 재귀적으로 반복합니다.",
      "Répartit les valeurs autour d’un pivot, puis répète récursivement des deux côtés.",
      "Teilt Werte um ein Pivot-Element und wiederholt den Vorgang rekursiv auf beiden Seiten.",
    ),
    focus: localized(
      "note「pivot」を追い、基準値の選び方で分割の偏りがどう変わるか観察しましょう。",
      "Follow the “pivot” note and observe how its choice affects partition balance.",
      "跟随“pivot”提示，观察基准值的选择如何影响分区平衡。",
      "Sigue la nota «pivot» y observa cómo su elección afecta al equilibrio de las particiones.",
      "Acompanhe a nota “pivot” e observe como sua escolha afeta o equilíbrio das partições.",
      "‘pivot’ 메모를 따라 기준값 선택이 분할 균형에 어떤 영향을 주는지 보세요.",
      "Suivez la note « pivot » et observez comment son choix influence l’équilibre des partitions.",
      "Folge dem Hinweis „pivot“ und beobachte, wie seine Wahl die Ausgewogenheit der Teilungen beeinflusst.",
    ),
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n²)",
    trait: TRAITS.unstableRecursive,
  },
  "sort_examples/heap_sort.py": {
    title: "Heap Sort",
    summary: localized(
      "最大値を取り出しやすいヒープを作り、末尾へ一つずつ確定します。",
      "Builds a heap for fast maximum extraction, settling one value at the end each time.",
      "构建便于取出最大值的堆，并逐个把值确定到末尾。",
      "Construye un heap para extraer rápido el máximo y fija un valor al final en cada paso.",
      "Constrói um heap para extrair rapidamente o máximo e fixa um valor no final a cada passo.",
      "최댓값을 쉽게 꺼낼 수 있는 힙을 만들고 값을 하나씩 끝에 확정합니다.",
      "Construit un tas pour extraire rapidement le maximum et fixe une valeur à la fin à chaque étape.",
      "Baut einen Heap zur schnellen Entnahme des Maximums und legt bei jedem Schritt einen Wert am Ende fest.",
    ),
    focus: localized(
      "先頭の最大値が末尾へ移動した後、ヒープがどのように修復されるかを追いましょう。",
      "After the maximum moves to the end, follow how the heap repairs itself.",
      "最大值移到末尾后，观察堆如何重新恢复结构。",
      "Después de mover el máximo al final, sigue cómo se repara el heap.",
      "Depois que o máximo vai para o final, acompanhe como o heap é restaurado.",
      "맨 앞의 최댓값이 끝으로 이동한 뒤 힙이 다시 정리되는 과정을 따라가 보세요.",
      "Après le déplacement du maximum à la fin, suivez la reconstruction du tas.",
      "Nachdem das Maximum ans Ende verschoben wurde, beobachte, wie sich der Heap repariert.",
    ),
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    trait: TRAITS.unstableInPlace,
  },
  "sort_examples/counting_sort.py": {
    title: "Counting Sort",
    summary: localized(
      "値ごとの個数を数え、その個数ぶん小さい順に配列へ書き戻します。",
      "Counts each value, then writes values back in order according to those counts.",
      "统计每个值的出现次数，再按计数从小到大写回数组。",
      "Cuenta cada valor y luego los escribe en orden según esas cantidades.",
      "Conta cada valor e depois os escreve em ordem conforme essas contagens.",
      "각 값의 개수를 센 뒤 그 개수만큼 작은 값부터 배열에 다시 씁니다.",
      "Compte chaque valeur, puis les réécrit dans l’ordre selon ces quantités.",
      "Zählt jeden Wert und schreibt die Werte entsprechend ihrer Häufigkeit geordnet zurück.",
    ),
    focus: localized(
      "要素同士を一度も比較せず、書き戻しだけで整列する点に注目しましょう。",
      "Notice that it sorts by writing counts back, without comparing array elements.",
      "注意它无需比较数组元素，只通过计数回写完成排序。",
      "Observa que ordena escribiendo los conteos, sin comparar elementos del arreglo.",
      "Observe que ele ordena escrevendo as contagens, sem comparar elementos do array.",
      "배열 요소를 서로 비교하지 않고 개수만 다시 써서 정렬한다는 점을 보세요.",
      "Remarquez qu’il trie en réécrivant les comptes, sans comparer les éléments du tableau.",
      "Beobachte, dass ohne Elementvergleiche sortiert wird, indem nur die Häufigkeiten zurückgeschrieben werden.",
    ),
    best: "O(n+k)",
    average: "O(n+k)",
    worst: "O(n+k)",
    trait: TRAITS.nonComparisonExtraK,
  },
  "sort_examples/radix_sort.py": {
    title: "Radix Sort",
    summary: localized(
      "1の位、10の位と桁ごとに安定な並べ替えを繰り返します。",
      "Repeatedly performs a stable ordering by ones, tens, and higher digit places.",
      "按个位、十位及更高位依次进行稳定排序。",
      "Repite una ordenación estable por unidades, decenas y posiciones superiores.",
      "Repete uma ordenação estável por unidades, dezenas e casas superiores.",
      "일의 자리, 십의 자리처럼 각 자릿수별로 안정 정렬을 반복합니다.",
      "Effectue un tri stable successif sur les unités, dizaines et positions supérieures.",
      "Sortiert wiederholt stabil nach Einer-, Zehner- und höheren Stellen.",
    ),
    focus: localized(
      "note「place」が変わるたび、同じ値が桁の違いでどう移動するか見てみましょう。",
      "As the “place” note changes, watch values move according to each digit.",
      "随着“place”提示变化，观察值如何根据不同数位移动。",
      "Cuando cambie la nota «place», observa cómo se mueven los valores según cada dígito.",
      "Quando a nota “place” mudar, observe os valores se moverem conforme cada dígito.",
      "‘place’ 메모가 바뀔 때 값이 각 자릿수에 따라 이동하는 모습을 보세요.",
      "Quand la note « place » change, observez les valeurs se déplacer selon chaque chiffre.",
      "Beobachte bei jeder Änderung von „place“, wie sich Werte entsprechend der Ziffer bewegen.",
    ),
    best: "O(d(n+k))",
    average: "O(d(n+k))",
    worst: "O(d(n+k))",
    trait: TRAITS.stableExtraNK,
  },
  "sort_examples/cycle_sort.py": {
    title: "Cycle Sort",
    summary: localized(
      "各値の最終位置を数えて直接置き、循環する値を順番に入れ替えます。",
      "Counts each value’s final position, places it directly, then follows the resulting cycle.",
      "计算每个值的最终位置并直接放置，再沿着形成的循环继续交换。",
      "Calcula la posición final de cada valor, lo coloca directamente y sigue el ciclo resultante.",
      "Calcula a posição final de cada valor, coloca-o diretamente e segue o ciclo resultante.",
      "각 값의 최종 위치를 계산해 바로 놓고, 이어지는 순환을 따라 값을 교환합니다.",
      "Calcule la position finale de chaque valeur, la place directement puis suit le cycle obtenu.",
      "Bestimmt die Endposition jedes Werts, platziert ihn direkt und folgt dann dem entstehenden Zyklus.",
    ),
    focus: localized(
      "比較は多くても、配列への書き込み回数が少なく抑えられる点を観察しましょう。",
      "Observe how it keeps array writes low even though it performs many comparisons.",
      "观察它虽然进行了许多比较，却能把数组写入次数保持得很低。",
      "Observa cómo mantiene pocas escrituras en el arreglo aunque realiza muchas comparaciones.",
      "Observe como ele mantém poucas escritas no array apesar das muitas comparações.",
      "비교는 많지만 배열에 쓰는 횟수는 적게 유지되는 점을 살펴보세요.",
      "Observez comment il limite les écritures dans le tableau malgré de nombreuses comparaisons.",
      "Beobachte, wie trotz vieler Vergleiche nur wenige Schreibvorgänge im Array nötig sind.",
    ),
    best: "O(n²)",
    average: "O(n²)",
    worst: "O(n²)",
    trait: TRAITS.minimumWrites,
  },
};
